### ISSUE TITLE
Sessions problem

### ISSUE THREAD

**Issue by Dwayneten** [Dwayneten/OnlineTeachingSystem#2]
Could not transport session data between diffrent controller.

e.g.
fail to get "Session["User"]" in HomeController.cs.

the session mentioned was set as user name in UserController.cs.

**Comment by Mimikami** [comment]
Here is the solve way->[session-is-null-when-calling-method-from-one-controller-to-another-mvc](http://stackoverflow.com/questions/31388357/session-is-null-when-calling-method-from-one-controller-to-another-mvc)@HuaFeng-Miki
//May be

**Comment by Mimikami** [comment]
And this is the others way to solve->[session-across-controller-becomes-null-in-mvc](http://stackoverflow.com/questions/11845000/session-across-controller-becomes-null-in-mvc)
